# 本文件采用 TOML 格式 https://toml.io/

# 文章标题 [请勿手动修改，会自动获取]
title = '''{{art.title}}'''

# 文章作者 [通常留空，自动等同于博客作者]
author = '''{{art.author}}'''

# 文章创建时间
ctime = '{{art.ctime}}'

# 文章修改时间
mtime = '{{art.mtime}}'

# sha1, 用来判断文章内容有无变更 [请勿手动修改]
checksum = '{{art.checksum}}'

# 自动替换。例:
# pairs =  [
#   [ '''../output/pics/abc.jpg''', '''https://example.com/abc.jpg''' ],
#   [ '''../output/pics/def.jpg''', '''https://example.com/def.jpg''' ],
# ]
pairs = [
{% for pair in art.pairs %}
  [
    {%- for item in pair -%}
    '''{{item}}''',
    {%- endfor -%}
  ],
{% endfor %}
]

